version: '3.9'

# Add your existing docker network name OR delete the networks block and 
# docker-compose will create one for the containers.
networks:
  default:
    external:
      name: <Your-Docker-Network>

services:
  bissues:
    image: bissues:latest
    container_name: dev
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_CONNECTION_STRING: "Server=postgres_image;Port=5432;Database=BissuesDB;Username=postgres;Password=Admin@123;"
      SEND_GRID_USER: <Your SendGrid User>
      SEND_GRID_EMAIL: <Your SendGrid Email>
      SEND_GRID_KEY: <Your SendGrid API Key>

  postgres_image:
    image: postgres:latest
    container_name: dev_db
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      # - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_DB: BissuesDB
      POSTGRES_PASSWORD: Admin@123
    # networks:
    #   - bissues-dev
volumes:
  db_volume:



